from dataclasses import dataclass
from typing import Optional

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError

from ..models import StatusEnum


DESKTOP_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
)


def settle(page, timeout=8000):
    """Wait for the page to go network-idle, capped short — some sites (analytics,
    live-chat widgets, trackers) never fully go idle, so a bare wait_for_load_state
    can hang for its full default timeout. If it doesn't settle in time, the page is
    almost always already usable, so we just proceed rather than fail the whole check."""
    try:
        page.wait_for_load_state("networkidle", timeout=timeout)
    except PlaywrightTimeoutError:
        pass


BLOCKED_PAGE_PATTERNS = [
    "access denied",
    "blocked by our security service",
    "processing your request",
    "powered and protected by",
    "checking your browser",
    "please verify you are a human",
    "request unsuccessful",
    "request could not be satisfied",
    "generated by cloudfront",
    "the request could not be satisfied",
    "403 error",
    "reference #",
]

MIN_CONTENT_LENGTH = 80


def page_looks_blocked(body_text: str) -> bool:
    """True if a page is (almost certainly) a bot-detection challenge/block page
    rather than real content — near-empty text, or a known block-page phrase.
    Callers should raise LookupBlocked rather than attempt extraction on such a page:
    an LLM asked to extract a status from a blocked page will happily hallucinate one."""
    stripped = body_text.strip()
    if len(stripped) < MIN_CONTENT_LENGTH:
        return True
    low = stripped.lower()
    return any(p in low for p in BLOCKED_PAGE_PATTERNS)


@dataclass
class LookupResult:
    status: StatusEnum
    source_url: str
    raw_extract: str
    confidence: float
    screenshot_path: Optional[str] = None
    # Set when an adapter had to discover an identifier (e.g. Illinois' EIN) via
    # web search rather than reading it off the Company row. The caller persists
    # this back onto the company so future checks skip the search.
    discovered_ein: Optional[str] = None


class LookupNotFound(Exception):
    """Raised when the entity name returns no match on the authority site."""


class LookupBlocked(Exception):
    """Raised when the authority site blocks automated access (CAPTCHA etc.)."""


class MultipleMatchesFound(Exception):
    """Raised when a name search matches more than one distinct entity
    (e.g. a parent company with several subsidiary filings). Carries every
    match found so the caller can track each one as its own tracked entity.
    """

    def __init__(self, matches):
        self.matches = matches  # list of {"name": str, "href": str}
        super().__init__(f"{len(matches)} distinct entities matched")
